receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

connectors:
  spanmetrics:
    dimensions:
      - name: service_name
      - name: span_kind
      - name: span_name
      - name: http_route
      - name: db.operation
    histogram:
      explicit:
        buckets: [2ms, 5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1s, 2s, 5s, 10s]

exporters:
  prometheus:
    endpoint: 0.0.0.0:9464
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:
    send_batch_size: 1024
    timeout: 200ms
  memory_limiter:
    check_interval: 1s
    limit_mib: 512

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [memory_limiter]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger, spanmetrics]
